# Generated by Django 4.0.1 on 2022-03-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_pix', '0003_alter_charge_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='status',
            field=models.CharField(default='AGUARDANDO', max_length=50),
        ),
    ]
