# Generated by Django 4.0.4 on 2022-04-22 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_pix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Imagem_pix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_pix', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_nome', models.CharField(max_length=100)),
                ('produto_caregoria', models.CharField(blank=True, choices=[('imovel', 'Imoveis'), ('eletronicos', 'Eletrônicos'), ('veiculos', 'Veículos'), ('financeiro', 'Financeiro'), ('roupas', 'Roupas'), ('celulares', 'Celulares'), ('moveis', 'Moveis'), ('eletro_domesticos', 'Eletro Doméstico'), ('dinheiro', 'Dinheiro'), ('outros', 'Outros')], max_length=30, null=True)),
                ('produto_descricao', models.TextField(max_length=500)),
                ('produto_img', models.ImageField(blank=True, null=True, upload_to='img')),
                ('pagamento_tempo', models.CharField(blank=True, choices=[('M', 'Mensal'), ('T', 'Trimestral'), ('A', 'Anual'), ('V', 'Vitalicio')], max_length=30, null=True)),
                ('produto_pix', models.ImageField(blank=True, null=True, upload_to='img')),
                ('produto_valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('produto_dia_suporte', models.CharField(blank=True, max_length=100, null=True)),
                ('produto_horario_suporte', models.TimeField(blank=True, null=True)),
                ('produto_status', models.CharField(choices=[('D', 'Disponivel'), ('A', 'Atualizando'), ('C', 'Preenchido')], default='D', max_length=15)),
                ('produto_numeros', models.IntegerField(default=0, help_text='Quantidade disponivels')),
                ('produto_vendidos', models.IntegerField(blank=True, default=0, null=True)),
                ('produto_disponiveis', models.IntegerField(blank=True, default=0, null=True)),
                ('produto_reservados', models.IntegerField(blank=True, default=0, null=True)),
                ('valor_total_vendidos', models.DecimalField(blank=True, decimal_places=2, help_text='Valor total vendidos', max_digits=8, null=True)),
                ('data_criacao', models.DateField(auto_now=True, max_length=50)),
                ('produto_imagens', models.ManyToManyField(to='produtos.imagem')),
                ('usuario_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeusPedidos',
            fields=[
                ('nr_pedido', models.UUIDField(auto_created=True, default='6f8a429427eb4028b264410bd1504773', editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome_usuario', models.CharField(max_length=25, null=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('preco_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('numeros_comprados', models.CharField(blank=True, max_length=10000, null=True)),
                ('status_pedido', models.CharField(blank=True, choices=[('PG', 'Pago'), ('PD', 'Pendente'), ('CL', 'Cancelado')], max_length=20, null=True)),
                ('data_Pedido', models.DateTimeField(auto_now_add=True)),
                ('pagamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_pix.charge')),
                ('produto_id', models.ManyToManyField(to='produtos.produto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meu pedido',
                'verbose_name_plural': 'Meus pedidos',
            },
        ),
    ]
