# Generated by Django 4.0.4 on 2022-04-22 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meuspedidos',
            name='nr_pedido',
            field=models.UUIDField(auto_created=True, default='ce666e88b7994c4e9d00e1591e368661', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
