# Generated by Django 4.0.4 on 2022-04-26 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meuspedidos',
            name='nr_pedido',
            field=models.UUIDField(auto_created=True, default='70b53dedce04452fbfa8b3a69f1b5e28', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
