# Generated by Django 3.2.12 on 2022-03-31 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meuspedidos',
            name='nr_pedido',
            field=models.UUIDField(auto_created=True, default='e659a1a58ce1479d884aa0fd1d786f7d', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
