# Generated by Django 4.0.2 on 2022-03-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_meuspedidos_nr_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meuspedidos',
            name='nr_pedido',
            field=models.UUIDField(auto_created=True, default='7379529289a2466e8d9bdc495ad3f316', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
