# Generated by Django 4.0.4 on 2022-04-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_meuspedidos_nr_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meuspedidos',
            name='nr_pedido',
            field=models.UUIDField(auto_created=True, default='5bae76d98b7b4f84a7d0a5c50fd09bb3', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
