# Generated by Django 4.0.2 on 2022-04-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_meuspedidos_nr_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meuspedidos',
            name='nr_pedido',
            field=models.UUIDField(auto_created=True, default='529ae5aeb855422e92585bf26e9af34c', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
