# Generated by Django 4.0.4 on 2022-04-26 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_meuspedidos_nr_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meuspedidos',
            name='nr_pedido',
            field=models.UUIDField(auto_created=True, default='caed6de46cc645c6bc24e4d0a0a53787', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
