# Generated by Django 4.0.2 on 2022-04-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_meuspedidos_nr_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='produto_img',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='meuspedidos',
            name='nr_pedido',
            field=models.UUIDField(auto_created=True, default='e1de95b0925c40d09526a63dac1ce86d', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
