# Generated by Django 4.0.4 on 2022-04-22 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_meuspedidos_nr_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meuspedidos',
            name='nr_pedido',
            field=models.UUIDField(auto_created=True, default='6fd8e34a13204165b8ddcaf555ea2b70', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
