# Generated by Django 4.0.2 on 2022-04-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_alter_meuspedidos_nr_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meuspedidos',
            name='nr_pedido',
            field=models.UUIDField(auto_created=True, default='42b3ff89da5641e98d24005f05e9a0d4', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
