# Generated by Django 4.0.4 on 2022-04-26 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_alter_meuspedidos_nr_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meuspedidos',
            name='nr_pedido',
            field=models.UUIDField(auto_created=True, default='e07db5b75fee4ce9852595de12cdeaa6', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
