# Generated by Django 3.2.12 on 2022-04-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_alter_meuspedidos_nr_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meuspedidos',
            name='nr_pedido',
            field=models.UUIDField(auto_created=True, default='3b0c7a3794ad49239c3426d6e7648b05', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
