# Generated by Django 3.2.12 on 2022-04-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_alter_meuspedidos_nr_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meuspedidos',
            name='nr_pedido',
            field=models.UUIDField(auto_created=True, default='a8c978775a074e4fba52aee069aa8929', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
