# Generated by Django 4.0.4 on 2022-04-26 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_alter_meuspedidos_nr_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meuspedidos',
            name='nr_pedido',
            field=models.UUIDField(auto_created=True, default='f2f7dee58e4a4ff6af36e450f2d92c8e', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
