# Generated by Django 4.0.2 on 2022-04-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_alter_meuspedidos_nr_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='pagamento_tempo',
            field=models.CharField(blank=True, choices=[('M', 'Mensal'), ('T', 'Trimestral'), ('A', 'Anual'), ('V', 'Vitalicio')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='meuspedidos',
            name='nr_pedido',
            field=models.UUIDField(auto_created=True, default='243deb59b699446193a0016226ec99c1', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
