# Generated by Django 3.2.13 on 2022-04-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_produto_pagamento_tempo_alter_meuspedidos_nr_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meuspedidos',
            name='nr_pedido',
            field=models.UUIDField(auto_created=True, default='1a6ea51662be45e1901a61a11961773e', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
