# Generated by Django 3.2.13 on 2022-04-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0012_alter_meuspedidos_nr_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meuspedidos',
            name='nr_pedido',
            field=models.UUIDField(auto_created=True, default='e0d1b17a972d4ab09583e2bd5faf9e8e', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='meuspedidos',
            name='status_pedido',
            field=models.BooleanField(blank=True, default='', max_length=20, null=True),
        ),
    ]
