# Generated by Django 4.0.4 on 2022-04-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0012_alter_meuspedidos_nr_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meuspedidos',
            name='nr_pedido',
            field=models.UUIDField(auto_created=True, default='9973ecbbbf374befbe92384d9edbea4d', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
