# Generated by Django 3.2.13 on 2022-04-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0013_auto_20220426_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meuspedidos',
            name='numeros_comprados',
        ),
        migrations.AlterField(
            model_name='meuspedidos',
            name='nr_pedido',
            field=models.UUIDField(auto_created=True, default='63e8edc1a4434ebcb7cab8f934464ba7', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='meuspedidos',
            name='preco_unitario',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meuspedidos',
            name='status_pedido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meuspedidos',
            name='valor_total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
