# Generated by Django 4.0.4 on 2022-04-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0013_alter_meuspedidos_nr_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meuspedidos',
            name='nr_pedido',
            field=models.UUIDField(auto_created=True, default='fbdcd6a0756441e0895ed8bfba442592', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
