# Generated by Django 3.2.13 on 2022-04-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0015_auto_20220426_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meuspedidos',
            name='nr_pedido',
            field=models.UUIDField(auto_created=True, default='7634cdb1b942490fa108e8f1f5899369', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
