# Generated by Django 3.2.13 on 2022-04-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0016_alter_meuspedidos_nr_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meuspedidos',
            name='nr_pedido',
            field=models.UUIDField(auto_created=True, default='46e198375a144d79a0d0ef461ce7e7ef', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
