# Generated by Django 3.2.13 on 2022-04-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0017_alter_meuspedidos_nr_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem_pix',
            name='img_pix',
            field=models.ImageField(upload_to='img/pix'),
        ),
        migrations.AlterField(
            model_name='meuspedidos',
            name='nr_pedido',
            field=models.UUIDField(auto_created=True, default='91426544b59f40a99722985e2bc831cc', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='produto_pix',
            field=models.ImageField(blank=True, null=True, upload_to='img/pix'),
        ),
    ]
