# Generated by Django 3.2.13 on 2022-04-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0018_auto_20220426_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meuspedidos',
            name='nr_pedido',
            field=models.UUIDField(auto_created=True, default='dd890f5db2534009b16f908dea1ffd8c', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='produto_valor',
            field=models.IntegerField(),
        ),
    ]
