# Generated by Django 3.2.13 on 2022-04-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0019_auto_20220426_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meuspedidos',
            name='nr_pedido',
            field=models.UUIDField(auto_created=True, default='16b9de73eaf1452a81edaf4cf0e42abf', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='meuspedidos',
            name='quantidade',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
