# Generated by Django 3.2.13 on 2022-04-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0021_auto_20220426_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meuspedidos',
            name='nome_usuario',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='meuspedidos',
            name='nr_pedido',
            field=models.UUIDField(auto_created=True, default='dbb6e342647a45d19273605c009792ff', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
