# Generated by Django 3.2.13 on 2022-04-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0025_auto_20220426_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meuspedidos',
            name='nr_pedido',
            field=models.UUIDField(auto_created=True, default='012c77c85b124302ba942a6d39153ce9', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
