# Generated by Django 3.2.13 on 2022-04-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0027_auto_20220426_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meuspedidos',
            name='nr_pedido',
            field=models.UUIDField(auto_created=True, default='7b31c815d47749bfa2e0fb54bedde961', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
