# Generated by Django 3.2.13 on 2022-04-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0028_alter_meuspedidos_nr_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='produto_valor_tri',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='produto_valor_vitalicio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meuspedidos',
            name='nr_pedido',
            field=models.UUIDField(auto_created=True, default='2fb0b59cfb1540ac9286f79fd306215c', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
