# Generated by Django 4.0.4 on 2022-04-27 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0029_auto_20220426_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meuspedidos',
            name='nr_pedido',
            field=models.UUIDField(auto_created=True, default='2c29adc970c149b8a79601b45159bf4f', editable=False, primary_key=True, serialize=False),
        ),
    ]
