# Generated by Django 3.2.13 on 2022-04-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0039_alter_meuspedidos_comprovante_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='produto_favorito',
            field=models.BooleanField(default=False),
        ),
    ]
