# Generated by Django 3.2.13 on 2022-07-11 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0041_alter_produto_produto_caregoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='produto_valor_tri',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='produto_valor_vitalicio',
        ),
    ]
