# Generated by Django 3.2.13 on 2022-04-28 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_perfil',
            name='cep',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuario_perfil',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
