# Generated by Django 3.2.13 on 2022-04-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220427_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_perfil',
            name='cpf',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='usuario_perfil',
            name='telefone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
