# Generated by Django 3.2.12 on 2022-03-31 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='linguagems_progr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_ling', models.ImageField(upload_to='media/img_linguagem/')),
                ('nome', models.CharField(max_length=50, null=True)),
                ('nivel_conhecimento', models.CharField(choices=[('B', 'Basico'), ('M', 'Intermediario'), ('A', 'Avancado')], max_length=50, null=True)),
                ('descricao', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
