# Generated by Django 4.0.4 on 2022-04-26 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='linguagems_progr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_ling', models.ImageField(upload_to='media/img_linguagem/')),
                ('nome', models.CharField(max_length=50, null=True)),
                ('nivel_conhecimento', models.CharField(choices=[('B', 'Basico'), ('M', 'Intermediario'), ('A', 'Avancado')], max_length=50, null=True)),
                ('descricao', models.TextField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='linguagens_mais_usadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_ling_1', models.ImageField(upload_to='media/img_linguagem/')),
                ('nome_1', models.CharField(max_length=50, null=True)),
                ('nivel_conhecimento_1', models.CharField(choices=[('B', 'Basico'), ('M', 'Intermediario'), ('A', 'Avancado')], max_length=50, null=True)),
                ('descricao_1', models.TextField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao', models.TextField(blank=True, max_length=500, null=True)),
                ('img_projeto', models.ImageField(blank=True, null=True, upload_to='projetos')),
                ('link_github', models.CharField(blank=True, max_length=200, null=True)),
                ('tecnologias', models.ManyToManyField(blank=True, null=True, to='site_portifolio.linguagems_progr')),
            ],
        ),
    ]
