# Generated by Django 4.0.2 on 2022-04-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_portifolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='linguagens_mais_usadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_ling_1', models.ImageField(upload_to='media/img_linguagem/')),
                ('nome_1', models.CharField(max_length=50, null=True)),
                ('nivel_conhecimento_1', models.CharField(choices=[('B', 'Basico'), ('M', 'Intermediario'), ('A', 'Avancado')], max_length=50, null=True)),
                ('descricao_1', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
