# Generated by Django 3.2.13 on 2022-07-11 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_portifolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projeto',
            options={'ordering': ['-id']},
        ),
    ]
