# Generated by Django 4.0.2 on 2022-04-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_portifolio', '0002_linguagens_mais_usadas'),
    ]

    operations = [
        migrations.CreateModel(
            name='projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, null=True)),
                ('descricao', models.CharField(max_length=500, null=True)),
                ('img_projeto', models.FileField(upload_to='projetos')),
                ('tecnologias', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
