# Generated by Django 4.0.2 on 2022-04-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_portifolio', '0003_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='img_projeto',
            field=models.FileField(blank=True, null=True, upload_to='projetos'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='tecnologias',
        ),
        migrations.AddField(
            model_name='projeto',
            name='tecnologias',
            field=models.ManyToManyField(blank=True, null=True, to='site_portifolio.linguagems_progr'),
        ),
    ]
