# Generated by Django 4.0.2 on 2022-04-06 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_portifolio', '0004_alter_projeto_descricao_alter_projeto_img_projeto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='link_github',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
