# Generated by Django 4.0.4 on 2022-04-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_portifolio', '0006_alter_projeto_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='img_projeto',
            field=models.ImageField(blank=True, null=True, upload_to='projetos'),
        ),
    ]
